"""
动画相关常量定义
"""

# 菜单动画时长
MENU_ANIMATION_DURATION = 80
MENU_EXIT_DURATION = 60
LEVEL_SELECT_ANIMATION_DURATION = 80
LEVEL_SELECT_EXIT_DURATION = 60

# 植物选择动画
PLANT_SELECT_ANIMATION_DURATION = 60
PLANT_SELECT_EXIT_DURATION = 45

# 植物飞行动画
PLANT_FLYING_DURATION = 30
PLANT_FLYING_ARC_HEIGHT = -80

# 配置重载消息
CONFIG_RELOAD_MESSAGE_DURATION = 180

# 动画延迟
BUTTON_STAGGER_DELAY = 15
BUTTON_ANIMATION_DURATION = 30
BUTTON_EXIT_STAGGER_DELAY = 10